hydra:
  output_subdir: Null
  run:
    dir: .
  searchpath:
    - pkg://config

list_mode: ['all', 'model', 'image', 'video']
mode: all   
viz: True

img_path: asserts/1.jpg
video: asserts/1.avi  # video path or id camera

model_pose: asserts/hand_pose_resnet18_att_244_244.pth
model_classify: asserts/svmmodel.sav

defaults:
  - _self_

  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

